# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            'Edwin Brooks'
tagline:          'Portfolio'
description:      'Portfolio description'
url:              https://bcciconsulting.net
baseurl:          ''
github:           lzbrooks

author:
  name:           'Edwin Brooks'
  url:            https://github.com/lzbrooks

# Custom vars
version:          1.0.0

