# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            'Edwin Brooks'
tagline:          'Portfolio'
description:      'BCCI'
url:              https://bcciconsulting.net
baseurl:          ''
github:           lzbrooks

author:
  name:           'Edwin Brooks'
  github:         https://github.com/lzbrooks
  linkedin:       https://www.linkedin.com/in/edwin-brooks-202a9456/
  email:          mailto:edwin.brooks@bcciconsulting.net

# Custom vars
version:          1.0.0

